FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
RUN pip install streamlit

# Copy the rest of the application code
COPY frontend ./frontend

EXPOSE 8501
EXPOSE 8000

# Command to run the Streamlit app
CMD ["streamlit", "run", "frontend/chatbot_ui.py"]