apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: pankajshinde/on_prem_gen_ai_llm_v1:api-latest
        # image: vaibhavdagwalagivant/on_prem_gen_ai_llm_v1-onpremgenai
        ports:
        - containerPort: 8000
        env:
        - name: QDRANT_HOST
          value: qdrant
        - name: QDRANT_PORT
          value: "6333"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: api
