apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: pankajshinde/on_prem_gen_ai_llm_v1:streamlit-latest
        # image: vaibhavdagwalagivant/on_prem_gen_ai_llm_v1-onpremgenai
        ports:
        - containerPort: 8501
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 15
          periodSeconds: 20
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: streamlit
# spec:
#   ports:
#   - port: 8501
#     targetPort: 8501
#   selector:
#     app: streamlit

apiVersion: v1
kind: Service
metadata:
  name: streamlit
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001  # Choose a port between 30000-32767
