apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: watcher
        image: pankajshinde/on_prem_gen_ai_llm_v1:watcher-latest
        # image: vaibhavdagwalagivant/on_prem_gen_ai_llm_v1-onpremgenai
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: qdrant-data
          mountPath: ./data
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
      volumes:
      - name: qdrant-data
        persistentVolumeClaim:
          claimName: qdrant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: watcher
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: watcher
